import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Provider } from "./utils/provider"
import "./globals.css";
import Navmenu from "@/components/Navmenu";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} h-full bg-[#FFFFFF] dark:bg-[#0F0B17] text-[#22242C] selection:bg-[#0F0B17] dark:selection:text-[#06030B] selection:text-white dark:selection:bg-[#F3F3F3] dark:text-[#F2F3F3] duration-300 transition-all ease-in-out`}>
        {/* next theme provider via util.tsx */}
        <Provider>
          <Navmenu/>
          <main className="mx-auto max-w-[1120px]">
            {children}
            </main>
        </Provider>
      </body>
    </html>
  );
}
